### ISSUE TITLE
Please use full funcionality of the AutoExecConfig

### ISSUE THREAD

**Issue by Z-RAY-Z** [Franc1sco/Fortnite-Emotes-Extended#17]
I use you plugin and when new version come you add some cvars. And cfg file didn't update - i should add them manually.
Sometimes you use "AutoExecConfig_CreateConVar" and sometimes "CreateConVar". Why don't use "AutoExecConfig_CreateConVar" only?

**Comment by Franc1sco** [comment]
Fixed.
