### ISSUE TITLE
Arena Weapon Issue

### ISSUE THREAD

**Issue by LubricantJam** [Franc1sco/Fortnite-Emotes-Extended#6]
https://youtu.be/6S01_L1gEGQ

**Comment by Franc1sco** [comment]
try https://github.com/Franc1sco/Fortnite-Emotes-Extended/archive/dev.zip

**Comment by Franc1sco** [comment]
Ok already fixed here https://github.com/Franc1sco/Fortnite-Emotes-Extended

You are welcome
