### ISSUE TITLE
emote teleport bug

### ISSUE THREAD

**Issue by Uronic** [Franc1sco/Fortnite-Emotes-Extended#7]
I don't really know how to explain it so I figured the best way to show you was via a video.

https://www.youtube.com/watch?v=I2t1PKCelKY

**Comment by LubricantJam** [comment]
https://github.com/Franc1sco/Fortnite-Emotes-Extended/blob/0ca1b5e775494dfac73fe8c29803fb224169fd8d/addons/sourcemod/scripting/fortnite_emotes_extended.sp#L546

Comment this out and recompile.

**Comment by Uronic** [comment]
fixed thanks my dude

**Comment by LubricantJam** [comment]
You're welcome, let's hope this change happens to the main repo with some way to toggle. Perhaps a cvar, I would pull request but I can't currently.

**Comment by Franc1sco** [comment]
Fixed in the latest version.
