### ISSUE TITLE
Latest Update causing Segmentation Faults

### ISSUE THREAD

**Issue by LubricantJam** [Franc1sco/Fortnite-Emotes-Extended#8]
Unsure on the cause, might me when people run the command to open the menu but either way, something in the latest update is causing segmentation faults and crashing servers.

**Comment by Franc1sco** [comment]
Try the changes in the dev branch https://github.com/Franc1sco/Fortnite-Emotes-Extended/tree/dev

**Comment by LubricantJam** [comment]
Nope, causing the same issues.

**Comment by Franc1sco** [comment]
updated.

**Comment by LubricantJam** [comment]
Still the same I'm afraid.

**Comment by Franc1sco** [comment]
Ok tell me exactly after what commit it start to crash

**Comment by LubricantJam** [comment]
Well b362ad06ae0b4b4f2f0646c66414632f1af57fee wouldn't load on my server and then it started to work when uploading 4395d33321802e2cceea3a162ca6bafe0cabb50f but then the crashes happened. So it could be either those two. I am currently using d84ebbdb88d0b90707d98941bffedf846470467c

**Comment by Franc1sco** [comment]
I merged it with previous version, try https://github.com/Franc1sco/Fortnite-Emotes-Extended/tree/dev

**Comment by LubricantJam** [comment]
It seems to be working now, I also suggest turning down the volume of the music as it can be quite overbearing. I normally rock around 0.4.

https://github.com/Franc1sco/Fortnite-Emotes-Extended/blob/b12d87122438cf4ded484e7dba1fa73deb723f05/addons/sourcemod/scripting/fortnite_emotes_extended.sp#L490

**Comment by Franc1sco** [comment]
Ok updated to the master repo.


About sound i will add a cvar for it.
